name: Automatic Tests

on:
  push:
    branches: 
      - testing_framework
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt-get install gfortran-9
        sudo apt-get -y install cmake
    - name: Check dependencies
      run: |
        gfortran-9 --version
        cmake --version
    - name: Install BLAS and LAPACK libraries
      run: |
        sudo apt-get install libblas-dev
        sudo apt-get install liblapack-dev
        
    - name: Cache pFUnit
      id: pfunit-cache
      uses: actions/cache@v1
      with:
        path: tests/pFUnit/
        key: ${{ runner.os }}-pfunit
        
    - name: Get pFUnit
      if: steps.pfunit-cache.outputs.cache-hit != 'true'
      run: |
        cd tests
        git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
    - name: Build pFUnit
      if: steps.pfunit-cache.outputs.cache-hit != 'true'
      env: 
        CC: "/usr/bin/gcc-9"
        FC: "/usr/bin/gfortran-9"
      run: |
        cd tests/pFUnit
        mkdir build
        cd build
        cmake ..
    - name: Compile pFUnit
      if: steps.pfunit-cache.outputs.cache-hit != 'true'
      env: 
        CC: "/usr/bin/gcc-9"
        FC: "/usr/bin/gfortran-9"
      run: |
        cd tests/pFUnit/build
        make tests
        make install
        
    - name: Compile LEGOLAS
      run: make FC=gfortran-9
    - name: Compile tests 
      env:
        PFUNIT_DIR: "/home/runner/work/legolas/legolas/tests/pFUnit/build/installed"
      run: |
        cd tests
        make FC=gfortran-9
    - name: Run tests
      run: |
        cd tests
        ./test_legolas

      
