name: Automatic Tests

on:
  push:
    branches: 
      - master
      - testing_framework
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install gfortran-9
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt-get install gfortran-9
    - name: Check gfortran-9
      run: gfortran-9 --version
    - name: Install cmake
      run: sudo apt-get -y install cmake
    - name: Check cmake
      run: cmake --version
    - name: Install BLAS library
      run: sudo apt-get install libblas-dev
    - name: Install LAPACK library
      run: sudo apt-get install liblapack-dev
    - name: Get pFUnit
      run: |
        cd tests
        git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
    - name: Build pFUnit
      env: 
        CC: "/usr/bin/gcc-9"
        FC: "/usr/bin/gfortran-9"
      run: |
        cd tests/pFUnit
        mkdir build
        cd build
        cmake ..
    - name: Compile pFUnit 1/2 (tests)
      env: 
        CC: "/usr/bin/gcc-9"
        FC: "/usr/bin/gfortran-9"
      run: |
        cd tests/pFUnit/build
        make tests
    - name: Compile pFUnit 2/2 (install)
      env: 
        CC: "/usr/bin/gcc-9"
        FC: "/usr/bin/gfortran-9"
      run: |
        cd tests/pFUnit/build
        make install
    - name: Compile LEGOLAS
      run: make FC=gfortran-9
    - name: Compile tests 
      env:
        PFUNIT_DIR: "/home/runner/work/legolas/legolas/tests/pFUnit/build/installed"
      run: |
        cd tests
        make FC=gfortran-9
    - name: Run tests
      run: |
        cd tests
        ./test_legolas

      
