name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Fix version for now, 3.4 throws an error (see #101)
        pip install markdown==3.3.7
        pip install ford==6.1.13 graphviz
        sudo apt-get install graphviz
        pip install -U sphinx
        pip install numpydoc sphinx-rtd-theme lazy-object-proxy==1.4 sphinx-autoapi

    - name: Generate documentation
      run: |
        cd docs
        python generate_docs.py stable

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      # only deploy if the branch is master
      if: ${{ contains(github.ref, 'refs/heads/master') }}
      with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_STABLE }}
          external_repository: legolas-project/legolas.science-stable
          publish_branch: main
          publish_dir: ./docs
          cname: legolas.science
          enable_jekyll: true
          full_commit_message: 'stable: deploy legolas-project/legolas@${{ github.sha }}'
