name: legolas-core

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  CC: /usr/bin/gcc-9
  FC: /usr/bin/gfortran-9
  PFUNIT_DIR: /home/runner/work/legolas/legolas/tests/core_tests/pFUnit/build/installed

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt-get install gfortran-9
        sudo apt-get -y install cmake
        sudo apt-get install libblas-dev
        sudo apt-get install liblapack-dev
        gfortran-9 --version
        cmake --version

    - name: Cache pFUnit
      id: pfunit-cache
      uses: actions/cache@v1
      with:
        path: tests/core_tests/pFUnit/
        key: ${{ runner.os }}-pfunit

    - name: Build pFUnit
      if: steps.pfunit-cache.outputs.cache-hit != 'true'
      run: |
        cd tests/core_tests
        git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
        cd pFUnit
        mkdir build
        cd build
        cmake .. -DSKIP_MPI=YES -DSKIP_OPENMP=YES -DSKIP_FHAMCREST=YES
        make -j 2 tests
        make -j 2 install

    - name: Compilation
      run: |
        make FC=gfortran-9
        cd tests/core_tests
        make FC=gfortran-9

    - name: Test Legolas core
      run: |
        cd tests/core_tests
        ./test_legolas_core
